post create functionality is implemented
bounswe/2021SpringGroup10 pull request #187
Opened 2021-12-12 15:39 UTC by tahakalkanli

Create post functionality is implemented. However it works with static data you can find in `src/fakeAPI.js`.

2021-12-12 17:37 UTC, gkberk requested changes
Location data is not stored. If you could fix these, it seems awesome! Well done.

2021-12-12 17:37 UTC, gkberk commented on purbee_frontend/src/components/createpost/post_fields.js
> +                {postType.fields.locationList.map((dateListField, index) => (
dateListField seems irrelevant here, is it a typo?

2021-12-12 17:37 UTC, gkberk commented on purbee_frontend/src/components/createpost/post_fields.js
> +                            {dateListField.header}
also here, did you mean mapListField?

2021-12-14 09:16 UTC, tahakalkanli commented
required changes fulfilled. backend connection still awaits.

2021-12-14 09:16 UTC, merged